kanban_board/urls.py
from django.urls import path
from . import views

app_name='kanban_board'

urlpatterns = [
    path('<uuid:id>/', views.kanban_board, name='board'),
    path('move-element/', views.change_element_status, name='move_element'),
    path('', views.board_panel, name='panel'),
]

kanban_board/models.py
import uuid

from django.db import models
from django.utils.translation import gettext_lazy as _
from typing import List
from model_utils.managers import InheritanceManager
from ordered_model.models import OrderedModel
from simple_history.models import HistoricalRecords
from django.contrib.auth.models import User, Group 


class Workflow(models.Model):
    name = models.CharField(_("WorkflowName"), max_length=255)

    def __str__(self):
        return self.name


class KanbanBoardState(OrderedModel):
    workflow = models.ForeignKey("Workflow", on_delete=models.CASCADE)
    name = models.CharField(_("KanbanBoardStateName"), max_length=255)
    order_with_respect_to = 'workflow'

    def __str__(self):
        return self.workflow.name + ": " + self.name
    
    class Meta(OrderedModel.Meta):
        ordering = ('order',)


class KanbanBoard(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False)
    name = models.CharField(_("KanbanBoardName"), max_length=255)
    workflow = models.ForeignKey("Workflow", on_delete=models.PROTECT)

    allowed_users = models.ManyToManyField(User)
    allowed_groups = models.ManyToManyField(Group)

    class Meta:
        app_label = 'kanban_board'
    
    def __str__(self):
        return self.name
    
    def kanban_board_grouped_elements(self):
        states = list(KanbanBoardState.objects.filter(workflow=self.workflow))
        board_elements = list(KanbanBoardElement.objects.filter(kanban_board_parent=self).select_subclasses())
        elements_grouped = {x: [] for x in states}
        for element in board_elements:
            if element.kanban_board_state is not None:
                elements_grouped[element.kanban_board_state].append(element)
        return elements_grouped


class KanbanBoardElement(models.Model):
    id = models.UUIDField(primary_key=True, unique=True, default=uuid.uuid4, editable=False)
    kanban_board_state = models.ForeignKey("KanbanBoardState", on_delete=models.SET_NULL, null=True, blank=True, editable=False)
    kanban_board_parent = models.ForeignKey("KanbanBoard", on_delete=models.SET_NULL, null=True, blank=True)

    kanban_board_fields: List[str] = []

    objects = InheritanceManager()

    changed_by = models.ForeignKey('auth.User', null=True, blank=True, on_delete=models.SET_NULL)
    history = HistoricalRecords()

    def kanban_board_field_tuples(self):
        return [(x.name, str(getattr(self, x.name))) for x in self._meta.fields if x.name in self.kanban_board_fields]
    
    def save(self, *args, **kwargs):
        if self.kanban_board_state is None and self.kanban_board_parent is not None:
            self.kanban_board_state = self.kanban_board_parent.workflow.kanbanboardstate_set.first()
        super(KanbanBoardElement, self).save(*args, **kwargs)

    @property
    def _history_user(self):
        return self.changed_by

    @_history_user.setter
    def _history_user(self, value):
        self.changed_by = value


    class Meta:
        app_label = 'kanban_board'

kanban_board/views.py
from django.shortcuts import render
from .models import KanbanBoard, KanbanBoardElement, KanbanBoardState
from django.http import JsonResponse, HttpResponse
from uuid import UUID
from django.views.decorators.csrf import csrf_protect
from django.conf import settings
from django.contrib.auth.decorators import permission_required
import json

@csrf_protect
@permission_required('kanban_board.kanban_board.view', login_url=settings.LOGIN_URL)
def kanban_board(request, id):
    board = KanbanBoard.objects.get(pk=id)
    elements_grouped = board.kanban_board_grouped_elements()
    
    return render(request, 'kanban_board/board.html', 
        context={
            "kanban_board": board, 
            "kanban_board_elements": elements_grouped,
        })

@permission_required('kanban_board.kanban_board.view', login_url=settings.LOGIN_URL)
def board_panel(request):
    boards = KanbanBoard.objects.all()
    return render(request, 'kanban_board/panel.html', 
        context={
            "kanban_boards": boards, 
        })

def element(request, model, id):
    pass

@csrf_protect
@permission_required('kanban_board.kanban_board_element.change', login_url=settings.LOGIN_URL)
def change_element_status(request):
    # check method
    if not request.method == "POST":
        return JsonResponse({"error": "bad_method", "details": "expected POST but got " + str(request.method)}, status=405)

    # get all required parameters
    data = json.loads(request.body)
    parent_id = UUID(data.get('kb_parent_id'))
    element_id = UUID(data.get('kb_element_id'))
    new_status = int(data.get('kb_new_status'))

    # validate if all required parameters are present
    missing_params = []
    for param in [element_id, new_status, parent_id]:
        if param is None:
            missing_params.append(param)
    if len(missing_params) > 0:
        return JsonResponse({"error": "missing_parameters", "details": missing_params}, status=422)

    # actual logic
    board = KanbanBoard.objects.get(pk=parent_id)
    el = KanbanBoardElement.objects.get(pk=element_id)
    el.kanban_board_state = board.workflow.kanbanboardstate_set.get(pk=new_status)
    el.save()

    return JsonResponse({}, status=200)
    

kanban_board/templates/kanban_board/_board.html
{% extends "kanban_board/_root.html" %}
{% regroup kanban_board_elements by kanban_board_state as kanban_board_grouped_elements %}
{% block kanban_board_content %}
    <div class="kanban-board">
        <div class="kanban-board-grid">
            {% for column in kanban_board_grouped_elements %}
                <div class="kanban-board-column">
                    <div class="kanban-board-column-header">
                        <h2>{{ column.grouper }}</h2>
                    </div>
                    <div class="kanban-board-column-content">
                        {% for element in column.list %}
                        <div class="kanban-board-element">
                            {% for field in element.kanban_board_field_tuples %}
                                <p>{{ field.0 }} - {{ field.1 }}</p>
                            {% endfor %}
                        </div>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

kanban_board/templates/kanban_board/_root.html
{% extends "base.html" %}
<div class="kanban-board-module">
    {% block kanban_board_content %}{% endblock %}
</div>

kanban_board/templates/kanban_board/board.html
{% extends "kanban_board/root.html" %}
{% block kanban_board_inner_content %}
    <section class="kanban-board text-gray-700 body-font">
        {% csrf_token %}
        <div class="px-5 mx-auto">
            <div class="flex flex-wrap w-full mb-10 flex-col items-center text-center">
                <h1 class="sm:text-5xl text-2xl font-medium title-font mb-2 text-gray-900">{{ kanban_board.name }}</h1>
            </div>
            <div class="flex -m-4">
                {% for column, values in kanban_board_elements.items %}
                    <div class="xl:w-1/3 md:w-1/2 p-4">
                        <div class="border border-gray-300 p-6 rounded-lg">
                            <div class="flex flex-wrap w-full mb-5 flex-col items-center text-center">
                                <h2 class="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">{{ column.name }}</h2>
                            </div>
                            <div class="mb-2">
                                {% for element in values %}
                                <div class="kanban-board-element border border-gray-300 rounded-lg mb-2">
                                    <div class="flex flex-col sm:flex-row sm:items-center items-start mx-auto">
                                        <div>
                                            {% if not forloop.parentloop.first %}
                                                <button data-link="{% url 'kanban_board:move_element' %}" data-target-state="{{ column.previous.pk }}" data-board="{{ kanban_board.pk }}" data-element="{{ element.pk }}" class="kanban-board-move flex-shrink-0 text-white bg-indigo-500 border-0 py-2 px-2 focus:outline-none hover:bg-indigo-600 rounded text-lg mt-10 sm:mt-0">
                                                    &lt;
                                                </button>
                                            {% endif %}
                                        </div>
                                        <div class="p-2 flex-grow">
                                            <h3 class="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">{{ element }}</h3>
                                            {% for field in element.kanban_board_field_tuples %}
                                                <p class="leading-relaxed text-base"><b>{{ field.0 }}:</b>&nbsp;{{ field.1 }}</p>
                                            {% endfor %}
                                        </div>
                                        <div>
                                            {% if not forloop.parentloop.last %}
                                                <button data-link="{% url 'kanban_board:move_element' %}" data-target-state="{{ column.next.pk }}" data-board="{{ kanban_board.pk }}" data-element="{{ element.pk }}" class="kanban-board-move flex-shrink-0 text-white bg-indigo-500 border-0 py-2 px-2 focus:outline-none hover:bg-indigo-600 rounded text-lg mt-10 sm:mt-0">
                                                    &gt;
                                                </button>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

kanban_board/templates/kanban_board/panel.html
{% extends "kanban_board/root.html" %}
{% block kanban_board_inner_content %}
<section class="text-gray-700 body-font">
    <div class="container px-5 mx-auto">
        <div class="flex flex-wrap w-full mb-10 flex-col items-center text-center">
            <h1 class="sm:text-5xl text-2xl font-medium title-font mb-2 text-gray-900">Boards</h1>
        </div>
        <div class="flex items-center lg:w-3/5 mx-auto border-b pb-4 mb-10 border-gray-500 sm:flex-row flex-col">
            <div class="flex-grow sm:text-left text-center mt-6 sm:mt-0">
                {% for board in kanban_boards %}
                    <h2 class="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900"><a href="{{ request.path }}{{ board.id }}">{{ board.name }}</a></h2>
                    <div class="flex flex-wrap w-full flex-col">
                        {% for key, value in board.kanban_board_grouped_elements.items %}
                            <h3>{{ key.name }}: {{ value|length }} </h3>
                        {% endfor %}
                    </div>
                    <h3></h3>
                {% endfor %}
            </div>
        </div>
    </div>
</section>
{% endblock %}

kanban_board/templates/kanban_board/root.html
{% extends "base.html" %}
{% load static %}
{% block kanban_board_content %}
<div class="kanban-board-module">
    {% block kanban_board_inner_content %}{% endblock %}
</div>
<script src="{% static 'kanban_board/js/kanbanboard.js' %}"></script> 
{% endblock %}